---
kind: "Component"
spec:
  type: "Service"
  lifecycle: "production"
  owner: "cdplayacc"
  system: "cd"
apiVersion: "backstage.io/v1alpha1"
metadata:
  name: manager
  description: Harness CurrentGen Manager
  tags: [java]
  links:
    - title: repo
      url: https://github.com/harness/harness-core
  annotations:
    harness.io/cd-serviceId: "Sidd-Service-managment"
    backstage.io/kubernetes-label-selector: 'app=manager'
    harness.io/ci-pipelineIds: OpenJdk11UBIFeatureBuildHarnessCore
    harness.io/projects: FEATUREBUILDS
    harness.io/project-url: https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/ci/orgs/default/projects/FEATUREBUILDS/dashboard
    harness.io/project-url-stage: https://stage.harness.io/ng/account/wFHXHD0RRQWoO8tIZT5YVw/cd/orgs/Harness/projects/Operations/deployments
    harness.io/projects-stage: Operations,RELEASEMANAGEMENT
    harness.io/cd-serviceId-stage: manager
    harness.io/ci-pipelineIds-stage: BuildUBItargetReleaseBranchQA
    jira/project-key: CDS
    pagerduty.com/service-id: P1MCPZK
    github.com/project-slug: harness/harness-core
    grafana/dashboard-selectors:
      - "folderUrl == 'https://<grafana-url>/dashboards/f/1z0BEDzIk/system_health'"
      - "folderUrl == 'https://<grafana-url>/dashboards/f/VUX4mTqVk/platform'" 
    grafana/overview-dashboard:
      - 'http://grafana/d/mToVpMeVk/microservices-health-dashboard?orgId=1'
      - 'http://grafana/d/n5w7gA94k/perpetual-tasks?orgId=1'
      - 'http://grafana/d/y5I3FbrVk/delegates-summary?orgId=1'
      - 'http://grafana/d/Xus3WJr4z/delegate-tasks?orgId=1'
